### ISSUE TITLE
clear_bitmap() not working?

### ISSUE THREAD

**Issue by ratkingsminion** [TheSos/allegrojs#11]
It seems `clear_bitmap()` isn't doing anything at all, probably because `fillRect()` just does an overlay, not a replacement of colors. So clearing a context with a transparent color does nothing.
If I replace the code of `clear_bitmap()` with `bitmap.context.clearRect(0, 0, bitmap.w, bitmap.h);` it works for me. `clear_to_color()` probably needs to get changed too, by adding this line of code at the top, in order to prevent problems with colors with alpha < 255.

**Comment by TheSos** [comment]
Pulled your request of that!
