### ISSUE TITLE
Loop method is slow

### ISSUE THREAD

**Issue by lainz** [TheSos/allegrojs#26]
Hi, please change 'loop' with 'requestAnimationFrame', all games run smoothly with that.

Check this, is the same game as in your website, but has that change applied:
https://lainz.github.io/AllegroPas2JS-Demo-Game/index.html

**Comment by lainz** [comment]
Oh, already in a pull request!

**Comment by dos1** [comment]
Yeah, #25 has a bunch of important fixes necessary for Allegro.js to work properly, including `requestAnimationFrame` support :)
