### ISSUE TITLE
rect parameters naming incorrect

### ISSUE THREAD

**Issue by wyszo** [TheSos/allegrojs#4]
rect takes x1, y1, x2, y2 as parameters while it should be: x1, y1, width, height (due to the way it's implemented; doesn't work as expected right now)

**Comment by ratkingsminion** [comment]
Well, to be exact, the implementation should be changed, not the parameter names. Just to keep the "compatibility" with the original Allegro.

**Comment by TheSos** [comment]
I need to do that! Apologies!

**Comment by wyszo** [comment]
You provided a functional library for free and apologise that there's a small bug in there o.O Wow. Thx for open sourcing the lib, was perfect for what I needed to do.

**Comment by TheSos** [comment]
Cheers! ratkingsminion fixed that! Yay!
