### ISSUE TITLE
Default font?

### ISSUE THREAD

**Issue by ratkingsminion** [TheSos/allegrojs#8]
I guess it's only a minor issue - if it's an issue at all - but this is how a Allegro.js game looks on Firefox: http://i.imgur.com/xoTZ55t.jpg and here it is on Chrome: http://i.imgur.com/zwaFwfg.jpg

So obviously there is no real standard font - is this expected behaviour? I'd like my games to be consistent on all browsers.

**Comment by TheSos** [comment]
Makes sense! It should be a super cool font, tho, and not GPL'd! I'll look around!

**Comment by TheSos** [comment]
Can we move this to the forums? :) http://allegrojs.net/forum/viewtopic.php?pid=9#p9

**Comment by TheSos** [comment]
Done!
